export const FakeCardsSet = [
  {
    id: 1,
    title: "Cambridge Vocabulary for IELTS (20 units)",
    words_number: 200,
    members: 112,
    type: "ielts",
    user: "Bao Nhom Ho Sy",
    avatar:
      "https://png.pngtree.com/png-clipart/20200224/original/pngtree-cartoon-color-simple-male-avatar-png-image_5230557.jpg",
  },
  {
    id: 2,
    title: "Cambridge Vocabulary for IELTS (20 units)",
    words_number: 200,
    members: 112,
    user: "Bao Nhom Ho Sy",
    avatar:
      "https://png.pngtree.com/png-clipart/20200224/original/pngtree-cartoon-color-simple-male-avatar-png-image_5230557.jpg",
  },
  {
    id: 3,
    title: "Cambridge Vocabulary for IELTS (20 units)",
    words_number: 200,
    members: 112,
    type: "ielts",
    user: "Bao Nhom Ho Sy",
    avatar:
      "https://png.pngtree.com/png-clipart/20200224/original/pngtree-cartoon-color-simple-male-avatar-png-image_5230557.jpg",
  },
  {
    id: 4,
    title: "Cambridge Vocabulary for IELTS (20 units)",
    words_number: 200,
    members: 112,
    type: "ielts",
    user: "Bao Nhom Ho Sy",
    avatar:
      "https://png.pngtree.com/png-clipart/20200224/original/pngtree-cartoon-color-simple-male-avatar-png-image_5230557.jpg",
  },
];
export const FakeCardsSetElement = {
  id: 1,
  title: "Cambridge Vocabulary for IELTS (20 units)",
  type: "ielts",
  user: "Bao Nhom Ho Sy",
  avatar:
    "https://png.pngtree.com/png-clipart/20200224/original/pngtree-cartoon-color-simple-male-avatar-png-image_5230557.jpg",
  cards: [
    {
      id: 1,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
    {
      id: 2,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
    {
      id: 3,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
    {
      id: 4,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
    {
      id: 5,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
    {
      id: 6,
      word: "Abandon",
      ipa: "/əˈbændən/",
      type: "verb",
      en_term: "To stop doing an activity before you have finished it",
      vi_term: "Từ bỏ, đầu hàng, không làm nữa",
      image: "https://kenh14cdn.com/2019/1/9/4-15470500556681296679573.jpg",
      examples: [
        "He abandoned his car when it broke down.",
        "She abandoned her baby.",
        "The game was abandoned because of the rain.",
      ],
    },
  ],
};
